model:
  name: "cardiffnlp/twitter-roberta-base-sentiment-latest"
  pretrained: true
  drop_out: 0.2
  momentum: 0.9
  hidden_size: 768
  aug: 0.1
  num_layers: 2
  local: true
  local_path: "RoBERTa/models"
  local_model_name: "model_epoch_2.pt"

training:
  epochs: 3
  batch_size: 8
  learning_rate: 2e-5
  eps: 5e-9
  weight_decay: 6e-06
  save_interval: 100
  enable_wandb: true

data:
  train_path: "RoBERTa/data/train/Twitter_Data.csv"
  validate_path: ""
  test_path: ""

environment:
  device: "cuda"
  num_workers: 4
